import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./modules/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#171717",
        "on-primary": "#ffffff",
        "accent-blue": "#0070f3",
        ink: "#171717",
        body: "#4d4d4d",
        mute: "#888888",
        "ink-muted": "#4d4d4d",
        "ink-subtle": "#888888",
        canvas: "#ffffff",
        "canvas-soft": "#fafafa",
        "canvas-soft-2": "#f5f5f5",
        "surface-1": "#ffffff",
        "surface-2": "#fafafa",
        "surface-3": "#f5f5f5",
        hairline: "#ebebeb",
        "hairline-strong": "#a1a1a1",
        "hairline-soft": "#fafafa",
        "inverse-canvas": "#171717",
        "inverse-ink": "#ffffff",
        link: "#0070f3",
        "link-deep": "#0761d1",
        success: "#0070f3",
        error: "#ee0000",
        warning: "#f5a623",
        "product-terraform": "#0070f3",
        "product-terraform-bright": "#0051c3",
        "product-vault": "#f5a623",
        "product-consul": "#ee0000",
        "product-waypoint": "#0070f3",
        "product-waypoint-deep": "#0051c3",
        "product-vagrant": "#0070f3",
        "product-nomad": "#0070f3",
        "product-boundary": "#ee0000",
        "amber-100": "#fff7e6",
        "amber-200": "#f5a623",
        "blue-7": "#0070f3",
        "semantic-success": "#0070f3",
        "semantic-warning": "#f5a623",
        "semantic-error": "#ee0000",
        "semantic-visited": "#8b5cf6",
        dark: {
          canvas: "#0a0a0a",
          "canvas-soft": "#111111",
          "canvas-soft-2": "#1a1a1a",
          ink: "#ededed",
          body: "#a1a1a1",
          mute: "#666666",
          hairline: "#2a2a2a",
          "hairline-strong": "#444444",
        },
      },
      fontFamily: {
        sans: [
          "Geist",
          "Inter",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
        mono: [
          "Geist Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "monospace",
        ],
      },
      fontSize: {
        "display-xl": ["48px", { lineHeight: "48px", fontWeight: "600", letterSpacing: "-2.4px" }],
        "display-lg": ["32px", { lineHeight: "40px", fontWeight: "600", letterSpacing: "-1.28px" }],
        "display-md": ["24px", { lineHeight: "32px", fontWeight: "600", letterSpacing: "-0.96px" }],
        "display-sm": ["20px", { lineHeight: "28px", fontWeight: "600", letterSpacing: "-0.6px" }],
        headline: ["32px", { lineHeight: "40px", fontWeight: "600", letterSpacing: "-1.28px" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600", letterSpacing: "-0.6px" }],
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "600", letterSpacing: "-0.32px" }],
        "card-title": ["16px", { lineHeight: "24px", fontWeight: "600", letterSpacing: "-0.32px" }],
        subhead: ["24px", { lineHeight: "32px", fontWeight: "600", letterSpacing: "-0.96px" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        body: ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md-strong": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400", letterSpacing: "-0.28px" }],
        "body-sm-strong": ["14px", { lineHeight: "20px", fontWeight: "500", letterSpacing: "-0.28px" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "caption-mono": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        code: ["13px", { lineHeight: "20px", fontWeight: "400" }],
        button: ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "button-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "button-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        eyebrow: ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        xxl: "24px",
        pill: "9999px",
        full: "9999px",
      },
      spacing: {
        hair: "1px",
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        section: "96px",
      },
      maxWidth: {
        content: "1280px",
      },
    },
  },
  plugins: [],
}
export default config
