SLANG_MAP: dict[str, str] = {
    "lol": "laughing out loud",
    "lmao": "laughing my ass off",
    "lolz": "laughing out loud",
    "rofl": "rolling on the floor laughing",
    "omg": "oh my god",
    "omfg": "oh my fucking god",
    "wtf": "what the fuck",
    "wth": "what the hell",
    "afk": "away from keyboard",
    "brb": "be right back",
    "btw": "by the way",
    "idk": "i don't know",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "irl": "in real life",
    "jk": "just kidding",
    "tbh": "to be honest",
    "ttyl": "talk to you later",
    "np": "no problem",
    "nvm": "never mind",
    "smh": "shaking my head",
    "thx": "thanks",
    "ty": "thank you",
    "yw": "you're welcome",
    "pls": "please",
    "plz": "please",
    "bc": "because",
    "cuz": "because",
    "b/c": "because",
    "gonna": "going to",
    "wanna": "want to",
    "gotta": "got to",
    "kinda": "kind of",
    "sorta": "sort of",
    "outta": "out of",
    "lotsa": "lots of",
    "bff": "best friend forever",
    "dm": "direct message",
    "fomo": "fear of missing out",
    "ftw": "for the win",
    "icymi": "in case you missed it",
    "nsfw": "not safe for work",
    "tmi": "too much information",
    "afaik": "as far as i know",
    "asap": "as soon as possible",
    "bae": "before anyone else",
    "diy": "do it yourself",
    "ez": "easy",
    "fam": "family",
    "fb": "facebook",
    "ffs": "for fuck's sake",
    "fwiw": "for what it's worth",
    "gj": "good job",
    "gtg": "got to go",
    "hmu": "hit me up",
    "idc": "i don't care",
    "ily": "i love you",
    "iirc": "if i recall correctly",
    "ikr": "i know right",
    "ily2": "i love you too",
    "lmk": "let me know",
    "l8r": "later",
    "msg": "message",
    "ne1": "anyone",
    "obvi": "obviously",
    "omw": "on my way",
    "pov": "point of view",
    "prolly": "probably",
    "rly": "really",
    "rn": "right now",
    "srsly": "seriously",
    "stfu": "shut the fuck up",
    "tgif": "thank god it's friday",
    "tho": "though",
    "u": "you",
    "ur": "your/you are",
    "wb": "welcome back",
    "wyd": "what you doing",
    "wym": "what you mean",
    "yolo": "you only live once",
    "afaic": "as far as i'm concerned",
    "cya": "see you",
    "gr8": "great",
    "ilyt": "i love you too",
    "k": "okay",
    "kk": "okay",
    "luv": "love",
    "ma": "mother",
    "pa": "father",
    "sis": "sister",
    "bro": "brother",
    "ya": "you",
    "yeet": "throw forcefully",
    "finna": "going to",
    "tryna": "trying to",
    "ain't": "am not",
    "don't": "do not",
    "can't": "cannot",
    "won't": "will not",
    "shouldn't": "should not",
    "wouldn't": "would not",
    "couldn't": "could not",
    "isn't": "is not",
    "aren't": "are not",
    "wasn't": "was not",
    "weren't": "were not",
    "hasn't": "has not",
    "haven't": "have not",
    "doesn't": "does not",
    "didn't": "did not",
    "i'm": "i am",
    "i've": "i have",
    "i'll": "i will",
    "i'd": "i would",
    "you're": "you are",
    "you've": "you have",
    "you'll": "you will",
    "you'd": "you would",
    "he's": "he is",
    "she's": "she is",
    "it's": "it is",
    "we're": "we are",
    "we've": "we have",
    "they're": "they are",
    "they've": "they have",
    "that's": "that is",
    "what's": "what is",
    "who's": "who is",
    "there's": "there is",
    "here's": "here is",
    "lemme": "let me",
    "gimme": "give me",
    "tell'em": "tell them",
    "gotcha": "got you",
}
